CREATE TABLE JUMPER_COMPETITION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    birthdate DATE NOT NULL
);

CREATE TABLE JUMPER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    birthdate DATE NOT NULL
);

CREATE TABLE COMPETITION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ski_jump VARCHAR(30) NOT NULL,
    country VARCHAR(30) NOT NULL,
    type_id BIGINT NOT NULL
);

CREATE TABLE TYPE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    height VARCHAR(30) NOT NULL,
    type VARCHAR(30) NOT NULL
);

CREATE TABLE PART (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    jumper_id BIGINT NOT NULL,
    competition_id BIGINT NOT NULL
);

ALTER TABLE PART
    ADD CONSTRAINT jumper_competition_part_id
    FOREIGN KEY (jumper_id) REFERENCES JUMPER_COMPETITION(id);

ALTER TABLE PART
    ADD CONSTRAINT competition_part_id
    FOREIGN KEY (competition_id) REFERENCES COMPETITION(id);

ALTER TABLE COMPETITION
    ADD CONSTRAINT type_competition_id
    FOREIGN KEY (type_id) REFERENCES TYPE(id);